# Generated by Django 5.2.4 on 2025-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('desc', models.CharField(default='', max_length=420)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='dapp/images')),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
