# Generated by Django 5.2.4 on 2025-07-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0004_kitchen_items_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(default='', max_length=254)),
                ('_subject', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=620)),
            ],
        ),
    ]
