# Generated by Django 5.2.4 on 2025-07-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='message',
        ),
    ]
