# Generated by Django 5.2.4 on 2025-07-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0006_rename_desc_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_items',
            name='desc',
            field=models.CharField(default='', max_length=1020),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='', max_length=1020),
        ),
    ]
