# Generated by Django 5.2.4 on 2025-08-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0007_alter_kitchen_items_desc_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proudname', models.CharField(default='', max_length=120)),
                ('desc', models.CharField(default='', max_length=1020)),
                ('disprice', models.IntegerField(default=0)),
                ('orgprice', models.IntegerField(default=0)),
                ('dist', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='dapp/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
