# Generated by Django 5.2.4 on 2025-08-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0008_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='disprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='proudname',
            new_name='product_name',
        ),
    ]
