# Generated by Django 5.2.4 on 2025-08-07 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0010_alter_discount_pub_date_alter_kitchen_items_pub_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='kitchen_items',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='kitchen_items',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dapp.kitchencategory'),
        ),
    ]
