# Generated by Django 5.2.4 on 2025-08-07 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0011_kitchencategory_alter_kitchen_items_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchencategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='kitchen_items',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_items', to='dapp.kitchencategory'),
        ),
    ]
