# Generated by Django 5.2.4 on 2025-08-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0012_remove_kitchencategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_items',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_items', to='dapp.kitchencategory'),
        ),
        migrations.AlterField(
            model_name='kitchencategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
