# Generated by Django 5.2.4 on 2025-08-09 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0013_alter_kitchen_items_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('desc', models.CharField(default='', max_length=1020)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='dapp/images')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Instant_Gyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('desc', models.CharField(default='', max_length=1020)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='dapp/images')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Regulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('desc', models.CharField(default='', max_length=1020)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='dapp/images')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Valves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=120)),
                ('desc', models.CharField(default='', max_length=1020)),
                ('price', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='dapp/images')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
