# Generated by Django 5.2.4 on 2025-08-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0014_accessories_instant_gyser_regulator_valves'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offermsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
